 create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `users` add unique `users_email_unique`(`email`);
 create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `password_resets` add index `password_resets_email_index`(`email`);
 create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`);
 create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`);
 alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`);
 create table `galleries` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `caption` varchar(255) not null, `image_url` varchar(255) not null, `description` mediumtext not null, `author_id` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `galleries` add index `galleries_author_id_index`(`author_id`);
 create table `gallery_items` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `content` mediumtext not null, `heading` varchar(255) not null, `gallery_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `gallery_items` add index `gallery_items_gallery_id_index`(`gallery_id`);
 create table `posts` (`id` bigint unsigned not null auto_increment primary key, `image_url` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `description` mediumtext not null, `author_id` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `posts` add index `posts_author_id_index`(`author_id`);
 create table `post_items` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `content` mediumtext not null, `author_id` bigint unsigned null, `post_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `post_items` add index `post_items_author_id_index`(`author_id`);
 alter table `post_items` add index `post_items_post_id_index`(`post_id`);
 create table `tags` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `category` varchar(120) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 create table `taggables` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `tag_id` bigint unsigned not null, `taggeable_type` varchar(255) not null, `taggeable_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `taggables` add index `taggables_taggeable_type_taggeable_id_index`(`taggeable_type`, `taggeable_id`)       ;
 alter table `taggables` add index `taggables_tag_id_index`(`tag_id`);
 create table `services` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `image_url` varchar(255) not null, `thumbnail_image_url` varchar(255) null, `description` mediumtext not null, `name` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 create table `media_owners` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `media_type` varchar(255) not null, `url` varchar(255) not null, `thumbnail_url` varchar(255) null, `owner_type` varchar(255) not null, `owner_id` bigint unsigned not null, `fs` varchar(12) not null default 'local') default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `media_owners` add index `media_owners_owner_type_owner_id_index`(`owner_type`, `owner_id`);
 alter table `posts` add `thumbnail_image_url` varchar(255) null;
alter table `media_owners` add `image_options` json null;
alter table `galleries` add `image_options` json null;
alter table `posts` add `image_options` json null;
alter table `services` add `image_options` json null;

 create table `user_roles` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `user_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
 alter table `user_roles` add index `user_roles_user_id_index`(`user_id`);
